spring:
  application:
    name: jobms
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
     enabled: true
#  datasource:
#      url: jdbc:postgresql://localhost:5432/jobapp
#      username: siva
#      password: siva
#      driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true


server:
  port: 8081