
info:
  app:
    name: Full Java-Spring-Boot-Microservices-with-k8s-Docker-AWS
    version: 1.0.0
    description: This is a Microservices application with Java-Spring-Boot-Microservices-with-k8s-Docker-AWS>
spring:
  application:
    name: firstjobapp
  jpa:
    hibernate:
     ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/firstjobapp
    username: postgres
    password: siva
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true


server:
  port: 8080

