spring:
  application:
    name: firstjobapp
  jpa:
    hibernate:
     ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
server:
  port: 8080

